services:
  api:
    build: .
    ports:
      - "87:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      lightfoot:
        aliases:
          - "fleet-ai.app.local"
      caddy_web:
        aliases:
          - api
    volumes:
      - ./cache:/app/cache

networks:
  lightfoot:
    external: true
  caddy_web:
    external: true